[bug 1085618] Rework qunit test to be faster and correct
The previous version of the qunit test used nose generators to split
each qunit test into a nose test. That's great, but the setup/teardown
was "shared" by all the tests which means they had to run in a specific
order with teardown as the last test. That breaks the requirement that
tests run independently of one another in any order.

Further, the setup actually executed at collection time, so it'd spin
up a browser with the qunit page and then at some point down the line,
the tests would run and examine the contents of that browser window.

This rewrite fixes that by squashing it into one nose test. It prints
output like this for individual test failures:

QUNIT FAIL: in "declarative": None != None

======================================================================
FAIL: kitsune/sumo/tests/test_qunit.py:TestQunit.test_qunit
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/willkg/mozilla/kitsune/kitsune/sumo/tests/test_qunit.py",
line 59, in test_qunit
    eq_(total_fails, 0, 'One or more Qunit tests failed; see output for
details')
  File
"/home/willkg/.virtualenvs/kitsune/lib/python2.7/site-packages/nose/tools.py",
line 31, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: One or more Qunit tests failed; see output for details

It'll print a QUNIT FAIL line for each test that failed.